[package]
name = "remote_shutdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
systray = "0.4.0"
winreg = "0.10"

[build-dependencies]
embed-resource = "2.3"
