[package]
name = "remote_shutdown"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.3.0"

tray-icon = "0.19.2"
[target.'cfg(windows)'.dependencies]
winreg = "0.10"
[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.12.0"
gtk = "0.18"
uinput = "0.1.3"

[build-dependencies]
[target.'cfg(windows)'.build-dependencies]
embed-resource = "2.3"
